<?php

namespace lunity\network\packet\raknet;

use lunity\network\packet\Packet;

class ConnectionRequestAccepted extends Packet {

    public static $id = 0x10;
    public $address;
    public $port;
    public $systemindex = 0;
    public $internalId = "255.255.255.255";
    public $ping;


    public function encode() {
        parent::encode(); // TODO: Change the autogenerated stub
        $this->putAddress($this->address, $this->port);
        $this->putShort($this->systemindex);
        for ($i = 1; $i <= 10; $i++) {
            $this->putAddress($this->internalId, 19132);
        }
        $this->putLong($this->ping);
        $this->putLong(bcadd($this->ping, "1000"));


    }

}
