<?php


namespace lunity\network\packet\raknet;


use lunity\network\packet\Packet;

class OpenConnectionRequest2 extends Packet {

    public static $id = 0x07;

    public $address = "";
    public $port = 0;
    public $mtu;
    public $guid;

    public function decode() {
        parent::decode(); // TODO: Change the autogenerated stub
        $this->offset += 16;
        $this->getAddress($this->address, $this->port);
        $this->mtu = $this->getShort();
        $this->guid = $this->getLong();
    }

}